#!/usr/bin/env node

// start-dev.mjs — local development launcher.
//
// Guarantees:
//   1. Local Supabase stack is running (starts it otherwise).
//   2. `.env.local` points at the LOCAL Supabase instance, not prod —
//      even if the user previously ran `start:prod`.
//   3. Expo starts with extra CLI args forwarded (e.g. --android).

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function run(command, args, opts = {}) {
  const child = spawnSync(command, args, {
    stdio: 'inherit',
    shell: process.platform === 'win32',
    ...opts,
  });
  return child.status ?? 1;
}

function runCapture(command, args) {
  const child = spawnSync(command, args, {
    stdio: ['ignore', 'pipe', 'pipe'],
    shell: process.platform === 'win32',
    encoding: 'utf8',
  });
  return { status: child.status ?? 1, stdout: child.stdout ?? '', stderr: child.stderr ?? '' };
}

function isSupabaseRunning() {
  const check = spawnSync('supabase', ['status'], {
    stdio: 'ignore',
    shell: process.platform === 'win32',
  });
  return check.status === 0;
}

function parseStatusEnv(output) {
  const map = {};
  for (const rawLine of output.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    map[line.slice(0, eq).trim()] = value;
  }
  return map;
}

function writeEnvLocal(values) {
  const target = resolve(process.cwd(), '.env.local');
  const lines = [
    '# Auto-generated by scripts/start-dev.mjs — do not edit by hand.',
    '# Values come from `supabase status -o env` for the local stack.',
    `EXPO_PUBLIC_SUPABASE_URL=${values.API_URL ?? ''}`,
    `EXPO_PUBLIC_SUPABASE_ANON_KEY=${values.ANON_KEY ?? ''}`,
    `EXPO_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${values.ANON_KEY ?? ''}`,
    '',
  ];
  writeFileSync(target, lines.join('\n'));
}

async function seedPrompts(apiUrl, serviceRoleKey) {
  const headers = {
    apikey: serviceRoleKey,
    Authorization: `Bearer ${serviceRoleKey}`,
  };
  const storageBase = `${apiUrl}/storage/v1`;

  // Create bucket if it doesn't exist
  await fetch(`${storageBase}/bucket`, {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify({ id: 'prompts', name: 'prompts', public: true }),
  });

  const promptsDir = resolve(process.cwd(), 'supabase/prompts');
  const files = ['chat_solo.txt', 'chat_couple.txt'];

  for (const file of files) {
    const check = await fetch(`${storageBase}/object/prompts/${file}`, { headers });
    if (check.ok) continue;

    const content = readFileSync(resolve(promptsDir, file));
    const res = await fetch(`${storageBase}/object/prompts/${file}`, {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'text/plain' },
      body: content,
    });
    if (res.ok) {
      console.log(`[start:dev] uploaded prompts/${file}`);
    } else {
      console.warn(`[start:dev] failed to upload prompts/${file}:`, await res.text());
    }
  }
}

if (!isSupabaseRunning()) {
  console.log('[start:dev] local Supabase is not running. Starting it...');
  const startCode = run('supabase', ['start']);
  if (startCode !== 0) process.exit(startCode);
}

const status = runCapture('supabase', ['status', '-o', 'env']);
if (status.status !== 0) {
  console.error('[start:dev] failed to read `supabase status -o env`:');
  console.error(status.stderr);
  process.exit(status.status);
}

const values = parseStatusEnv(status.stdout);
if (!values.API_URL || !values.ANON_KEY) {
  console.error('[start:dev] could not find API_URL / ANON_KEY in supabase status output.');
  process.exit(1);
}

writeEnvLocal(values);
console.log('[start:dev] wrote .env.local pointing at local Supabase.');

await seedPrompts(values.API_URL, values.SERVICE_ROLE_KEY);

const forwardedArgs = process.argv.slice(2);
const expoCode = run('expo', ['start', ...forwardedArgs]);
process.exit(expoCode);
